{{ config(materialized='view', tags=["m_FDS_UUBVI_ELIM_WORK_INIT_GPNG_FINC_INS_WRK"]) }}

-- SQ_CTRL_UUBVI_ELIM_WORK_INIT_GPNG_FINC_INS
with raw_source as (
    select * from {{ source('dbaall', 'CTRL_UUBVI_ELIM_WORK_INIT_GPNG_FINC_INS') }} CTRL_UUBVI_ELIM_WORK_INIT_GPNG_FINC_INS
),

source_data as (
    select
        src.acc_expo_yr_mm,
        src.assm_reins_agmt_anchr_id,
        src.bil_typ_cd,
        src.bulk_tran_ind,
        src.cls_cd,
        src.cede_reins_agmt_anchr_id,
        src.cml_agmt_anchr_id,
        src.cmtn_agmt_anchr_id,
        src.covg_cmpnt_anchr_id,
        src.crcy_cd,
        src.dac_cd,
        src.exc_cd,
        src.fin_acc_expo_yr_mm,
        src.fin_cyc_pst_dt,
        src.fin_pst_yr_mm,
        src.inmy_agmt_anchr_id,
        src.lob_za_gp_cd,
        src.finc_lob_za_gp_cd,
        src.mp_cd,
        src.opert_co_cd,
        src.org_id,
        src.pol_nbr,
        src.prem_postal_regn_anchr_id,
        src.reins_waqs_trty_cd,
        src.retro_ratg_cd,
        src.src_pol_eff_dt,
        src.susp_ind,
        src.prdr_nbr,
        src.st_nbr,
        src.src_cmtn_id,
        src.self_insd_retn_ind,
        src.pol_sym_cd,
        src.reins_agmt_id,
        src.pop_info_id,
        src.updt_pop_info_id,
        src.bat_id,
        src.waqs_ind,
        src.cmtn_ind,
        src.actl_los_rcvy_idm_amt,
        src.adjr_alae_amt,
        src.antcp_los_rcvy_alae_amt,
        src.antcp_los_rcvy_idm_amt,
        src.bab_unernd_prem_amt,
        src.bab_wr_comm_tot_amt,
        src.bab_wr_prem_amt,
        src.base_admin_fee_amt,
        src.base_prem_amt,
        src.cede_fee_amt,
        src.contr_can_paid_fee_amt,
        src.contr_trnsfr_fee_amt,
        src.delr_mrkp_amt,
        src.drcvy_alae_amt,
        src.drcvy_idm_los_amt,
        src.drcvy_rsv_alae_amt,
        src.drcvy_rsv_idm_amt,
        src.ernd_comm_amt,
        src.ernd_prem_amt,
        src.excs_tax_amt,
        src.ibnr_alae_itd_amt,
        src.ibnr_alae_prev_yye_amt,
        src.ibnr_ernd_prem_amt,
        src.ibnr_idm_itd_amt,
        src.ibnr_idm_prev_yye_amt,
        src.loss_fund_amt,
        src.loss_stblz_fee_amt,
        src.mgmt_ernd_base_admin_fee_amt,
        src.mgmt_ernd_base_prem_amt,
        src.mgmt_ernd_chrgcustcan_amt,
        src.mgmt_ernd_contr_trnsfr_fee_amt,
        src.mgmt_ernd_delr_mrkp_amt,
        src.mgmt_ernd_loss_fund_amt,
        src.mgmt_ernd_loss_stblz_fee_amt,
        src.mgmt_ernd_misc_prem_amt,
        src.mgmt_ernd_no_chrgbck_fee_amt,
        src.mgmt_ernd_nonrfnd_adv_fee_amt,
        src.mgmt_ernd_nonrfnd_promo_fee,
        src.mgmt_ernd_over_rmt_fee_amt,
        src.mgmt_ernd_prtnr_comm_fee_amt,
        src.mgmt_ernd_retro_fee_amt,
        src.mgmt_ernd_rfnd_adv_fee_amt,
        src.mgmt_ernd_rfnd_promo_fee_amt,
        src.mgmt_ernd_surty_prem_amt,
        src.mgmt_ernd_volm_disc_comm_amt,
        src.mgmt_ernd_volm_disc_prem_amt,
        src.misc_prem_amt,
        src.mnth_ibnr_alae_itd_amt,
        src.mnth_ibnr_idm_itd_amt,
        src.net_drcvy_slvg_subro_palae_amt,
        src.net_drcvy_slvg_subro_pidm_amt,
        src.net_of_drcvy_los_rsv_alae_amt,
        src.net_of_drcvy_los_rsv_idm_amt,
        src.no_chrgbck_fee_amt,
        src.nonrfnd_adv_fee_amt,
        src.nonrfnd_promo_fee_amt,
        src.over_rmt_fee_amt,
        src.pool_ibnr_chg_amt,
        src.prtnr_comm_fee_amt,
        src.retro_fee_amt,
        src.rfnd_adv_fee_amt,
        src.rfnd_promo_fee_amt,
        src.slvg_and_subro_alae_amt,
        src.slvg_and_subro_idm_amt,
        src.stat_comm_amt,
        src.statu_ernd_base_admin_fee_amt,
        src.statu_ernd_base_prem_amt,
        src.statu_ernd_chrgcustcan_amt,
        src.statu_ernd_contrtrnsfr_fee_amt,
        src.statu_ernd_delr_mrkp_amt,
        src.statu_ernd_loss_fund_amt,
        src.statu_ernd_loss_stblz_fee_amt,
        src.statu_ernd_misc_prem_amt,
        src.statu_ernd_no_chrgbck_fee_amt,
        src.statu_ernd_nonrfnd_adv_fee_amt,
        src.statu_ernd_nonrfnd_promo_fee,
        src.statu_ernd_over_rmt_fee_amt,
        src.statu_ernd_prtnr_comm_fee_amt,
        src.statu_ernd_retro_fee_amt,
        src.statu_ernd_rfnd_adv_fee_amt,
        src.statu_ernd_rfnd_promo_fee_amt,
        src.statu_ernd_surty_prem_amt,
        src.statu_ernd_volm_disc_comm_amt,
        src.statu_ernd_volm_disc_prem_amt,
        src.surty_prem_amt,
        src.ulae_amt,
        src.volm_disc_comm_amt,
        src.volm_disc_prem_amt,
        src.wr_expo_occr_amt,
        src.wr_prem_adt_amt,
        src.wr_prem_amt,
        src.wr_prem_can_f_amt,
        src.wr_prem_can_mid_amt,
        src.wr_prem_endt_amt,
        src.mgmt_cede_fee_amt,
        src.statu_cede_fee_amt,
        src.mgmt_excs_tax_amt,
        src.statu_excs_tax_amt,
        src.prem_tax_amt,
        src.mgmt_prem_tax_amt,
        src.statu_prem_tax_amt,
        src.asset_def_fee_amt,
        src.dlr_nbr,
        src.sale_dt,
        src.contr_typ_cd,
        src.sic_cd,
        src.undg_pgm_cd,
        src.pol_purp_typ_cd,
        src.cede_reins_agmt_id,
        src.cede_fee_pct,
        src.cmpny_cede_fee_uubvi_pct,
        src.ctry_cd,
        src.tot_comm_amt,
        src.nov_adj_ind,
        src.mgmt_ernd_scs_prem_comm_amt_1,
        src.mgmt_ernd_scs_prem_comm_amt_2,
        src.mgmt_ernd_scs_prem_comm_amt_3,
        src.mgmt_ernd_scs_prem_comm_amt_4,
        src.mgmt_ernd_scs_prem_comm_amt_5,
        src.statu_ernd_scs_prem_comm_amt_1,
        src.statu_ernd_scs_prem_comm_amt_2,
        src.statu_ernd_scs_prem_comm_amt_3,
        src.statu_ernd_scs_prem_comm_amt_4,
        src.statu_ernd_scs_prem_comm_amt_5,
        src.scs_prem_comm_amt_1,
        src.scs_prem_comm_amt_2,
        src.scs_prem_comm_amt_3,
        src.scs_prem_comm_amt_4,
        src.scs_prem_comm_amt_5,
        src.scs_prem_comm_amt_1 as mgmt_ernd_fsri_f_i_cede_fee_amt,
        src.scs_prem_comm_amt_2 as mgmt_ernd_fsri_f_i_excs_tax_amt,
        src.scs_prem_comm_amt_3 as mgmt_ernd_fsri_f_i_prem_tax_amt,
        src.scs_prem_comm_amt_4 as mgmt_ernd_fsri_f_i_base_prem_amt,
        src.scs_prem_comm_amt_5 as statu_ernd_fsri_f_i_cede_fee_amt,
        src.scs_prem_comm_amt_1 as statu_ernd_fsri_f_i_excs_tax_amt,
        src.scs_prem_comm_amt_2 as statu_ernd_fsri_f_i_prem_tax_amt,
        src.scs_prem_comm_amt_3 as statu_ernd_fsri_f_i_base_prem_amt,
        src.scs_prem_comm_amt_1 as fsri_f_i_cede_fee_amt,
        src.scs_prem_comm_amt_2 as fsri_f_i_excs_tax_amt,
        src.scs_prem_comm_amt_3 as fsri_f_i_prem_tax_amt,
        src.scs_prem_comm_amt_4 as fsri_f_i_base_prem_amt,
        src.assm_reins_agmt_anchr_id as finc_servs_rol_for_reins_reinsr_rol_plyr_anchr_id,
        src.cls_cd as src_sys_cd,
        src.assm_reins_agmt_anchr_id as change_rec_flag,
        src.nov_adj_ind as drvd_finc_los_catg_cd,
        src.assm_reins_agmt_anchr_id as seq_wrk_agmt_anchr_id,
        src.sale_dt as out_eff_to_tistmp,
        src.sale_dt as out_eff_fm_tistmp,
        src.assm_reins_agmt_anchr_id as v_elim_co_id,
        src.assm_reins_agmt_anchr_id as v_typ_id_co,
        src.assm_reins_agmt_anchr_id as v_uubvi_co_id,
        src.assm_reins_agmt_anchr_id as v_typ_id_org_id,
        src.prem_postal_regn_anchr_id as org_id_anchor_id,
        src.prem_postal_regn_anchr_id as fsp_contr_typ_cd,
        src.prem_postal_regn_anchr_id as out_typ_rol_plyr,
        src.assm_reins_agmt_anchr_id as out_agmt_anchr_id,
        src.sale_dt as out_pol_eff_dt,
        src.sale_dt as out_can_dt,
        src.sale_dt as out_end_dt,
        src.assm_reins_agmt_anchr_id as out_cml_agmt_anchr_id,
        src.lob_za_gp_cd as out_cml_agmt_anchr_id1,
        src.statu_ernd_scs_prem_comm_amt_4 as fsri_drcvy_paid_loss_pidm_amt,
        src.statu_ernd_scs_prem_comm_amt_5 as fsri_drcvy_slvg_subro_amt,
        src.scs_prem_comm_amt_1 as fsri_drcvy_alloc_loss_adj_rsv_amt,
        src.scs_prem_comm_amt_2 as fsri_drcvy_case_loss_rsv_amt,
        src.scs_prem_comm_amt_3 as fsri_drcvy_paid_loss_exp_plae_amt,
        src.scs_prem_comm_amt_4 as fsri_drcvy_paid_adj_palae_amt,
        src.scs_prem_comm_amt_5 as fsri_drcvy_ulae_comm_ulae_amt
    from raw_source src
)

select * from source_data

--End-DBShift