{{ config(materialized='table', tags=['m_FDS_UUBVI_ELIM_WORK_INIT_GPNG_FINC_INS_WRK']) }}

-- trans_exp_cml_agmt_insert_new.sql
with rtr_new_exist_cml_agmt as (
    select * from {{ ref('int_rtr_new_exist_cml_agmt') }}
),

trans_exp_cml_agmt_insert_new as (
    select
        sq.newlookuprow3 as newlookuprow3,
        sq.pol_purp_typ_cd3 as pol_purp_typ_cd,
        sq.out_agmt_anchr_id3 as out_agmt_anchr_id,
        sq.pol_nbr3 as pol_nbr,
        sq.inmy_agmt_anchr_id3 as inmy_agmt_anchr_id,
        sq.dlr_nbr3 as dlr_nbr,
        sq.pol_sym_cd3 as pol_sym_cd,
        sq.sic_cd3 as sic_cd,
        sq.undg_pgm_cd3 as undg_pgm_cd,
        sq.contr_typ_cd as contr_typ_cd,
        sq.org_id3 as org_id,
        sq.prdr_nbr3 as prdr_nbr,
        sq.st_nbr3 as st_nbr,
        sq.opert_co_cd3 as opert_co_cd,
        sq.eff_fm_tistmp3 as eff_fm_tistmp,
        sq.eff_to_tistmp3 as eff_to_tistmp,
        sq.pop_info_id3 as pop_info_id,
        sq.updt_pop_info_id3 as updt_pop_info_id,
        sq.bat_id3 as bat_id,
        sq.tran_curr_cd3 as tran_curr_cd,
        sq.out_pol_eff_dt3 as out_pol_eff_dt,
        1 as out_typ_id,
        'Y' as out_actv_rec_ind,
        '0' as out_acqn_cd,
        'N' as out_adt_freq_cd,
        'B' as out_bndl_cd,
        sq.out_can_dt3 as out_can_dt,
        'null' as out_can_rsn_cd,
        'N' as out_ciid_match_ind,
        'null' as out_cms_pty_id,
        'null' as out_cpan_ind,
        '2' as out_dac_cd,
        '9' as out_divd_par_cd,
        '9' as out_exc_cd,
        '0' as out_instl_cd,
        '00' as out_modu_nbr,
        '99' as out_mp_cd,
        sq.out_can_dt3 as out_plnd_end_dt,
        '4' as out_pol_contr_typ_cd,
        'null' as out_port_ind,
        iff(sq.pol_purp_typ_cd3='UUBVI','Dealer UUBVI Policy',iff(sq.pol_purp_typ_cd3='ELIM','Dealer Elimination Policy')) as out_pri_nmd_insd_nm,
        'UC' as out_prcg_ofc_cd,
        '1' as out_prdr_src_cd,
        'null' as out_ratg_ori_cd,
        'Y' as out_reins_waqs_trty_cd,
        'N' as out_renl_ind,
        '9' as out_retro_ratg_cd,
        '5' as out_rsk_typ_cd,
        'N' as out_self_insd_retn_ind,
        '19000101' as out_src_pol_eff_dt,
        'I' as out_sts_cd,
        'null' as out_v_inv_pool_ind,
        'SC' as out_bil_typ_cd,
        '19000101' as out_incp_dt,
        0 as out_agmt_term_in_mnth,
        'null' as out_mkt_cd,
        'null' as out_perf_prot_ind,
        sq.out_pol_eff_dt3 as out_sale_dt,
        iff(sq.pol_purp_typ_cd3='UUBVI','44',iff(sq.pol_purp_typ_cd3='ELIM','46')) as out_co_nbr_za,
        '1' as out_new_renl_cd,
        '9' as out_par_cd,
        '29991231' as out_pol_can_dt,
        'I' as out_pol_contr_sts_cd,
        '29991231' as out_pol_expi_dt,
        '00' as out_pol_modu_nbr,
        'Y' as out_reins_ind,
        '9' as out_retro_cd,
        'N' as out_sir_ind,
        'NW' as out_sys_src_cd,
        'N' as out_unbndl_ind,
        'REFI' as out_src_sys_cd,
        sq.v_typ_id_co3 as out_typ_id_company,
        sq.v_typ_id_org_id3 as out_typ_id_orgid,
        0 as out_rt,
        sq.out_end_dt3 as out_str_dt,
        sq.out_end_dt3 as out_end_dt,
        iff(sq.pol_purp_typ_cd3 = 'ELIM',sq.v_elim_co_id3,iff(sq.pol_purp_typ_cd3 = 'UUBVI',sq.v_uubvi_co_id3)) as out_elim_uubvi_companchrid,
        sq.org_id_anchor_id3 as org_id_anchor_id1,
        sq.delr_contr_typ_id3 as seq_cml_agmt_id,
        sq.org_id_anchor_id as org_id_anchor_id,
        sq.fsp_contr_typ_cd3 as fsp_contr_typ_cd,
        sq.out_typ_rol_plyr3 as out_typ_rol_plyr,
        sq.rol_plyr_anchr_id3 as rol_plyr_anchr_id3,
        sq.finc_servs_rol_id3 as finc_servs_rol_id3,
        sq.delr_contr_typ_id3 as delr_contr_typ_id3
    from rtr_new_exist_cml_agmt sq
)

select * from trans_exp_cml_agmt_insert_new

--End-DBShift