version: 2

sources:
  - name: PostgreSQL35W
    database: PostgreSQL35W
    schema: PostgreSQL35W
    tables:
      - name: ctrl_sprd_mnthly_amts_temp_1

models:
  - name: trans_exp_trl_sprd_2yr_last_mnth
  - name: trans_exp_eff_to
  - name: trans_exp_sprd_mnthly_prem_amt_calc
  - name: int_srt_trl_sprd_2yr_dates
  - name: stg_sq_ctrl_sprd_mnthly_amts_temp1
  - name: trans_exp_sprd_2yr_mnthly_prem_amt_calc
  - name: stg_sq_ctrl_sprd_mnthly_amts_temp
  - name: int_srt_dates
  - name: int_filt_not_trl_sprd_2yr_last_mnth
  - name: int_union_all_recs
  - name: int_agg_last_mnth
  - name: trans_exp_cal_lst_mnth
  - name: int_filtr_trl_sprd_2yr_term_recs
  - name: int_agg_trl_sprd_2yr_last_mnth
  - name: stg_tgt_ctrl_sprd_mnthly_amts
