-- trans_exp_trl_sprd_2yr_last_mnth.sql
{{ config(materialized='view', tags=["m_fds_ctrl_sprd_mnthly_amts_atomic_last_ins"]) }}

with int_agg_trl_sprd_2yr_last_mnth as (
    select
        prtclr_mony_provsn_id,
        etl_sys_nm,
        monthly_date,
        agmt_anchr_id,
        base_amt,
        daily_amt,
        trl_sprd_2yr_base_amt,
        trl_sprd_2yr_last_mnth_rem_days,
        trl_sprd_rem_term_dly_amt,
        prem_amt,
        prem_added_amt,
        eff_md_yr_mo,
        pop_info_id,
        batch_id,
        mnth_yr_part_eff_to,
        mnth_yr_part_last_day,
        mnth_yr_part_trl_sprd_2yr_last_day,
        covg_cmpnt_agmt_anchr_id,
        out_comm_amt,
        trl_sprd_2yr_comm_amt,
        trl_sprd_rem_term_comm_dly_amt,
        der_comm_amt,
        der_comm_added_amt,
        tran_prem_amt,
        tran_comm_amt,
        trl_sprd_2yr_tran_prem_amt,
        trl_sprd_rem_term_tran_prem_dly_amt,
        der_tran_prem_amt,
        der_tran_prem_added_amt,
        out_trl_sprd_2yr_tran_comm_amt,
        trl_sprd_rem_term_tran_comm_dly_amt,
        der_tran_comm_amt,
        der_tran_comm_added_amt,
        contr_prem_amt,
        trl_sprd_2yr_contr_prem_amt,
        trl_sprd_rem_term_contr_prem_dly_amt,
        der_contr_prem_amt,
        der_contr_prem_added_amt,
        src_ln_of_busn_cd,
        contr_comm_amt,
        trl_sprd_2yr_contr_comm_amt,
        trl_sprd_rem_term_contr_comm_dly_amt,
        der_contr_comm_amt,
        der_contr_comm_added_amt,
        crcy_cd,
        tran_crcy_cd,
        contr_crcy_cd
    from {{ ref('int_agg_trl_sprd_2yr_last_mnth') }}
),

trans_exp_trl_sprd_2yr_last_mnth as (
    select
        prtclr_mony_provsn_id,
        etl_sys_nm,
        monthly_date,
        agmt_anchr_id,
        base_amt,
        daily_amt,
        trl_sprd_2yr_base_amt,
        trl_sprd_2yr_last_mnth_rem_days,
        trl_sprd_rem_term_dly_amt,
        prem_amt,
        prem_added_amt,
        round( ( ( trl_sprd_2yr_base_amt - coalesce(prem_added_amt, 0) ) + (trl_sprd_2yr_last_mnth_rem_days * trl_sprd_rem_term_dly_amt) ), 2 ) as out_prem_amt,
        eff_md_yr_mo,
        pop_info_id,
        batch_id,
        mnth_yr_part_eff_to,
        mnth_yr_part_last_day,
        mnth_yr_part_trl_sprd_2yr_last_day,
        covg_cmpnt_agmt_anchr_id,
        out_comm_amt,
        trl_sprd_2yr_comm_amt,
        trl_sprd_rem_term_comm_dly_amt,
        der_comm_amt,
        der_comm_added_amt,
        round( ( ( trl_sprd_2yr_comm_amt - coalesce(der_comm_added_amt, 0) ) + ( trl_sprd_2yr_last_mnth_rem_days * trl_sprd_rem_term_comm_dly_amt) ), 2 ) as out_der_comm_amt,
        tran_prem_amt,
        tran_comm_amt,
        trl_sprd_2yr_tran_prem_amt,
        trl_sprd_rem_term_tran_prem_dly_amt,
        der_tran_prem_amt,
        der_tran_prem_added_amt,
        round( ( ( trl_sprd_2yr_tran_prem_amt - coalesce(der_tran_prem_added_amt, 0) ) + ( trl_sprd_2yr_last_mnth_rem_days * trl_sprd_rem_term_tran_prem_dly_amt) ), 2 ) as out_der_tran_prem_amt,
        out_trl_sprd_2yr_tran_comm_amt,
        trl_sprd_rem_term_tran_comm_dly_amt,
        der_tran_comm_amt,
        der_tran_comm_added_amt,
        round( ( ( out_trl_sprd_2yr_tran_comm_amt - coalesce(der_tran_comm_added_amt, 0) ) + ( trl_sprd_2yr_last_mnth_rem_days * trl_sprd_rem_term_tran_comm_dly_amt) ), 2 ) as out_der_tran_comm_amt,
        contr_prem_amt,
        trl_sprd_2yr_contr_prem_amt,
        trl_sprd_rem_term_contr_prem_dly_amt,
        der_contr_prem_amt,
        der_contr_prem_added_amt,
        round( ( ( trl_sprd_2yr_contr_prem_amt - coalesce(der_contr_prem_added_amt, 0) ) + ( trl_sprd_2yr_last_mnth_rem_days * trl_sprd_rem_term_contr_prem_dly_amt) ), 2 ) as out_der_contr_prem_amt,
        src_ln_of_busn_cd,
        contr_comm_amt,
        trl_sprd_2yr_contr_comm_amt,
        trl_sprd_rem_term_contr_comm_dly_amt,
        der_contr_comm_amt,
        der_contr_comm_added_amt,
        round( ( ( trl_sprd_2yr_contr_comm_amt - coalesce(der_contr_comm_added_amt, 0) ) + ( trl_sprd_2yr_last_mnth_rem_days * trl_sprd_rem_term_contr_comm_dly_amt) ), 2 ) as out_der_contr_comm_amt,
        crcy_cd,
        tran_crcy_cd,
        contr_crcy_cd
    from int_agg_trl_sprd_2yr_last_mnth
)

select * from trans_exp_trl_sprd_2yr_last_mnth
--End-DBShift