{{ config(materialized='table', tags=['m_FDS_CTRL_SPRD_MNTHLY_AMTS_ATOMIC_LAST_INS']) }}

-- int_agg_trl_sprd_2yr_last_mnth.sql
with srt_trl_sprd_2yr_dates as (
    select
        out_DER_CONTR_PREM_AMT,
        SRC_LN_OF_BUSN_CD41,
        out_CONTR_COMM_AMT41,
        out_TRL_SPRD_2YR_CONTR_COMM_AMT41,
        out_TRL_SPRD_REM_TERM_CONTR_COMM_DLY_AMT41,
        out_DER_CONTR_COMM_AMT41,
        CRCY_CD as CRCY_CD1,
        TRAN_CRCY_CD as TRAN_CRCY_CD1,
        CONTR_CRCY_CD as CONTR_CRCY_CD1,
        PRTCLR_MONY_PROVSN_ID,
        ETL_SYS_NM,
        MONTHLY_DATE,
        AGMT_ANCHR_ID as AGMT_ANCHR_ID1,
        BASE_AMT as BASE_AMT1,
        DAILY_AMT as DAILY_AMT1,
        TRL_SPRD_IND,
        MNTH_YR_PART_TRL_SPRD_2YR_LAST_DAY as MNTH_YR_PART_TRL_SPRD_2YR_LAST_DAY1,
        TRL_SPRD_2YR_BASE_AMT as TRL_SPRD_2YR_BASE_AMT1,
        TRL_SPRD_2YR_LAST_MNTH_REM_DAYS as TRL_SPRD_2YR_LAST_MNTH_REM_DAYS1,
        TRL_SPRD_REM_TERM_DLY_AMT as TRL_SPRD_REM_TERM_DLY_AMT1,
        PREM_AMT as PREM_AMT1,
        EFF_MD_YR_MO as EFF_MD_YR_MO1,
        POP_INFO_ID as POP_INFO_ID1,
        BATCH_ID as BATCH_ID1,
        MNTH_YR_PART_EFF_TO as MNTH_YR_PART_EFF_TO1,
        MNTH_YR_PART_LAST_DAY as MNTH_YR_PART_LAST_DAY1,
        COVG_CMPNT_AGMT_ANCHR_ID as COVG_CMPNT_AGMT_ANCHR_ID1,
        out_COMM_AMT as out_COMM_AMT1,
        TRL_SPRD_2YR_COMM_AMT as TRL_SPRD_2YR_COMM_AMT1,
        TRL_SPRD_REM_TERM_COMM_DLY_AMT as TRL_SPRD_REM_TERM_COMM_DLY_AMT1,
        out_DER_COMM_AMT,
        out_TRAN_PREM_AMT,
        TRAN_COMM_AMT as TRAN_COMM_AMT1,
        TRL_SPRD_2YR_TRAN_PREM_AMT as TRL_SPRD_2YR_TRAN_PREM_AMT1,
        TRL_SPRD_REM_TERM_TRAN_PREM_DLY_AMT as TRL_SPRD_REM_TERM_TRAN_PREM_DLY_AMT1,
        out_DER_TRAN_PREM_AMT,
        out_TRL_SPRD_2YR_TRAN_COMM_AMT as out_TRL_SPRD_2YR_TRAN_COMM_AMT1,
        TRL_SPRD_REM_TERM_TRAN_COMM_DLY_AMT as TRL_SPRD_REM_TERM_TRAN_COMM_DLY_AMT1,
        out_DER_TRAN_COMM_AMT,
        out_CONTR_PREM_AMT,
        out_TRL_SPRD_2YR_CONTR_PREM_AMT,
        out_TRL_SPRD_REM_TERM_CONTR_PREM_DLY_AMT
    from {{ ref('int_srt_trl_sprd_2yr_dates') }}
),

int_agg_trl_sprd_2yr_last_mnth as (
    select
        prtclr_mony_provsn_id,
        etl_sys_nm,
        max(agmt_anchr_id1) as agmt_anchr_id1,
        max(base_amt1) as base_amt1,
        max(daily_amt1) as daily_amt1,
        max(trl_sprd_ind) as trl_sprd_ind,
        max(mnth_yr_part_trl_sprd_2yr_last_day1) as mnth_yr_part_trl_sprd_2yr_last_day1,
        max(trl_sprd_2yr_base_amt1) as trl_sprd_2yr_base_amt1,
        max(trl_sprd_2yr_last_mnth_rem_days1) as trl_sprd_2yr_last_mnth_rem_days1,
        max(trl_sprd_rem_term_dly_amt1) as trl_sprd_rem_term_dly_amt1,
        max(prem_amt1) as prem_amt1,
        max(eff_md_yr_mo1) as eff_md_yr_mo1,
        max(pop_info_id1) as pop_info_id1,
        max(batch_id1) as batch_id1,
        max(mnth_yr_part_eff_to1) as mnth_yr_part_eff_to1,
        max(mnth_yr_part_last_day1) as mnth_yr_part_last_day1,
        max(covg_cmpnt_agmt_anchr_id1) as covg_cmpnt_agmt_anchr_id1,
        max(out_comm_amt1) as out_comm_amt1,
        max(trl_sprd_2yr_comm_amt1) as trl_sprd_2yr_comm_amt1,
        max(trl_sprd_rem_term_comm_dly_amt1) as trl_sprd_rem_term_comm_dly_amt1,
        max(out_der_comm_amt) as out_der_comm_amt,
        max(out_tran_prem_amt) as out_tran_prem_amt,
        max(tran_comm_amt1) as tran_comm_amt1,
        max(trl_sprd_2yr_tran_prem_amt1) as trl_sprd_2yr_tran_prem_amt1,
        max(trl_sprd_rem_term_tran_prem_dly_amt1) as trl_sprd_rem_term_tran_prem_dly_amt1,
        max(out_der_tran_prem_amt) as out_der_tran_prem_amt,
        max(out_trl_sprd_2yr_tran_comm_amt1) as out_trl_sprd_2yr_tran_comm_amt1,
        max(trl_sprd_rem_term_tran_comm_dly_amt1) as trl_sprd_rem_term_tran_comm_dly_amt1,
        max(out_der_tran_comm_amt) as out_der_tran_comm_amt,
        max(out_contr_prem_amt) as out_contr_prem_amt,
        max(out_trl_sprd_2yr_contr_prem_amt) as out_trl_sprd_2yr_contr_prem_amt,
        max(out_trl_sprd_rem_term_contr_prem_dly_amt) as out_trl_sprd_rem_term_contr_prem_dly_amt,
        max(out_der_contr_prem_amt) as out_der_contr_prem_amt,
        max(src_ln_of_busn_cd41) as src_ln_of_busn_cd41,
        max(out_contr_comm_amt41) as out_contr_comm_amt41,
        max(out_trl_sprd_2yr_contr_comm_amt41) as out_trl_sprd_2yr_contr_comm_amt41,
        max(out_trl_sprd_rem_term_contr_comm_dly_amt41) as out_trl_sprd_rem_term_contr_comm_dly_amt41,
        max(out_der_contr_comm_amt41) as out_der_contr_comm_amt41,
        max(crcy_cd1) as crcy_cd1,
        max(tran_crcy_cd1) as tran_crcy_cd1,
        max(contr_crcy_cd1) as contr_crcy_cd1,
        max(monthly_date) as out_monthly_date,
        max(agmt_anchr_id1) as agmt_anchr_id,
        max(base_amt1) as base_amt,
        max(daily_amt1) as daily_amt,
        max(mnth_yr_part_trl_sprd_2yr_last_day1) as mnth_yr_part_trl_sprd_2yr_last_day,
        max(trl_sprd_2yr_base_amt1) as trl_sprd_2yr_base_amt,
        max(trl_sprd_2yr_last_mnth_rem_days1) as trl_sprd_2yr_last_mnth_rem_days,
        max(trl_sprd_rem_term_dly_amt1) as trl_sprd_rem_term_dly_amt,
        max(prem_amt1) as prem_amt,
        sum(iff(mnth_yr_part_trl_sprd_2yr_last_day1 != mnth_yr_part_last_day1,prem_amt1,0)) as out_prem_added_amt,
        max(eff_md_yr_mo1) as eff_md_yr_mo,
        max(pop_info_id1) as pop_info_id,
        max(batch_id1) as batch_id,
        max(mnth_yr_part_eff_to1) as mnth_yr_part_eff_to,
        max(mnth_yr_part_last_day1) as mnth_yr_part_last_day,
        max(covg_cmpnt_agmt_anchr_id1) as covg_cmpnt_agmt_anchr_id,
        max(out_comm_amt1) as out_comm_amt,
        max(trl_sprd_2yr_comm_amt1) as trl_sprd_2yr_comm_amt,
        max(trl_sprd_rem_term_comm_dly_amt1) as trl_sprd_rem_term_comm_dly_amt,
        max(out_der_comm_amt) as der_comm_amt,
        sum(iff(mnth_yr_part_trl_sprd_2yr_last_day1 != mnth_yr_part_last_day1,out_der_comm_amt,0)) as out_der_comm_added_amt,
        max(out_tran_prem_amt) as tran_prem_amt,
        max(tran_comm_amt1) as tran_comm_amt,
        max(trl_sprd_2yr_tran_prem_amt1) as trl_sprd_2yr_tran_prem_amt,
        max(trl_sprd_rem_term_tran_prem_dly_amt1) as trl_sprd_rem_term_tran_prem_dly_amt,
        max(out_der_tran_prem_amt) as der_tran_prem_amt,
        sum(iff(mnth_yr_part_trl_sprd_2yr_last_day1 != mnth_yr_part_last_day1,out_der_tran_prem_amt,0)) as out_der_tran_prem_added_amt,
        max(out_trl_sprd_2yr_tran_comm_amt1) as out_trl_sprd_2yr_tran_comm_amt,
        max(trl_sprd_rem_term_tran_comm_dly_amt1) as trl_sprd_rem_term_tran_comm_dly_amt,
        max(out_der_tran_comm_amt) as der_tran_comm_amt,
        sum(iff(mnth_yr_part_trl_sprd_2yr_last_day1 != mnth_yr_part_last_day1,out_der_tran_comm_amt,0)) as out_der_tran_comm_added_amt,
        max(out_contr_prem_amt) as contr_prem_amt,
        max(out_trl_sprd_2yr_contr_prem_amt) as trl_sprd_2yr_contr_prem_amt,
        max(out_trl_sprd_rem_term_contr_prem_dly_amt) as trl_sprd_rem_term_contr_prem_dly_amt,
        max(out_der_contr_prem_amt) as der_contr_prem_amt,
        sum(iff(mnth_yr_part_trl_sprd_2yr_last_day1 != mnth_yr_part_last_day1,out_der_contr_prem_amt,0)) as out_der_contr_prem_added_amt,
        max(src_ln_of_busn_cd41) as src_ln_of_busn_cd,
        max(out_contr_comm_amt41) as contr_comm_amt,
        max(out_trl_sprd_2yr_contr_comm_amt41) as trl_sprd_2yr_contr_comm_amt,
        max(out_trl_sprd_rem_term_contr_comm_dly_amt41) as trl_sprd_rem_term_contr_comm_dly_amt,
        max(out_der_contr_comm_amt41) as der_contr_comm_amt,
        sum(iff(mnth_yr_part_trl_sprd_2yr_last_day1 != mnth_yr_part_last_day1,out_der_contr_comm_amt41,0)) as out_der_contr_comm_added_amt,
        max(crcy_cd1) as crcy_cd,
        max(tran_crcy_cd1) as tran_crcy_cd,
        max(contr_crcy_cd1) as contr_crcy_cd
    from srt_trl_sprd_2yr_dates
    group by
        prtclr_mony_provsn_id,
        etl_sys_nm
)

select * from int_agg_trl_sprd_2yr_last_mnth

--End-DBShift