-- int_agg_last_mnth.sql
{{ config(materialized='table', tags=['m_FDS_CTRL_SPRD_MNTHLY_AMTS_ATOMIC_LAST_INS']) }}

with int_srt_dates as (
    -- upstream model mapping ports to matching input port names
    select 
        PRTCLR_MONY_PROVSN_ID,
        ETL_SYS_NM,
        MONTHLY_DATE,
        AGMT_ANCHR_ID as AGMT_ANCHR_ID1,
        BASE_AMT as BASE_AMT1,
        DAILY_AMT,
        PREM_AMT as PREM_AMT1,
        EFF_MD_YR_MO as EFF_MD_YR_MO1,
        POP_INFO_ID as POP_INFO_ID1,
        BATCH_ID as BATCH_ID1,
        COVG_CMPNT_AGMT_ANCHR_ID as COVG_CMPNT_AGMT_ANCHR_ID1,
        out_COMM_AMT,
        out_DER_COMM_AMT,
        out_TRAN_PREM_AMT,
        TRAN_COMM_AMT as TRAN_COMM_AMT1,
        out_CONTR_PREM_AMT,
        MNTH_YR_PART_EFF_TO,
        MNTH_YR_PART_LAST_DAY,
        out_DER_TRAN_PREM_AMT as DER_TRAN_PREM_AMT,
        out_DER_TRAN_COMM_AMT as DER_TRAN_COMM_AMT,
        out_DER_CONTR_PREM_AMT as DER_CONTR_PREM_AMT,
        SRC_LN_OF_BUSN_CD41 as SRC_LN_OF_BUSN_CD411,
        out_CONTR_COMM_AMT41,
        out_DER_CONTR_COMM_AMT41 as DER_CONTR_COMM_AMT41,
        CRCY_CD as CRCY_CD1,
        TRAN_CRCY_CD as TRAN_CRCY_CD1,
        CONTR_CRCY_CD as CONTR_CRCY_CD1
    from {{ ref('int_srt_dates') }}
),
int_agg_last_mnth as (
    -- Aggregation logic
    select 
        PRTCLR_MONY_PROVSN_ID,
        ETL_SYS_NM,
        MAX(MONTHLY_DATE) as MONTHLY_DATE,
        MAX(AGMT_ANCHR_ID1) as AGMT_ANCHR_ID1,
        MAX(BASE_AMT1) as BASE_AMT1,
        MAX(DAILY_AMT) as DAILY_AMT,
        MAX(PREM_AMT1) as PREM_AMT1,
        MAX(EFF_MD_YR_MO1) as EFF_MD_YR_MO1,
        MAX(POP_INFO_ID1) as POP_INFO_ID1,
        MAX(BATCH_ID1) as BATCH_ID1,
        MAX(AGMT_ANCHR_ID1) as AGMT_ANCHR_ID,
        MAX(BASE_AMT1) as BASE_AMT,
        MAX(COVG_CMPNT_AGMT_ANCHR_ID1) as COVG_CMPNT_AGMT_ANCHR_ID1,
        MAX(out_COMM_AMT) as out_COMM_AMT,
        MAX(out_DER_COMM_AMT) as out_DER_COMM_AMT,
        MAX(out_TRAN_PREM_AMT) as out_TRAN_PREM_AMT,
        MAX(TRAN_COMM_AMT1) as TRAN_COMM_AMT1,
        MAX(PREM_AMT1) as PREM_AMT,
        MAX(out_CONTR_PREM_AMT) as out_CONTR_PREM_AMT,
        SUM(CASE WHEN MNTH_YR_PART_EFF_TO != MNTH_YR_PART_LAST_DAY THEN PREM_AMT1 ELSE 0 END) as out_ADDED_AMT,
        MAX(EFF_MD_YR_MO1) as EFF_MD_YR_MO,
        MAX(POP_INFO_ID1) as POP_INFO_ID,
        MAX(BATCH_ID1) as BATCH_ID,
        MAX(MNTH_YR_PART_EFF_TO) as MNTH_YR_PART_EFF_TO,
        MAX(MNTH_YR_PART_LAST_DAY) as MNTH_YR_PART_LAST_DAY,
        MAX(MONTHLY_DATE) as out_MONTHLY_DATE,
        MAX(COVG_CMPNT_AGMT_ANCHR_ID1) as COVG_CMPNT_AGMT_ANCHR_ID,
        MAX(out_COMM_AMT) as COMM_AMT,
        MAX(out_DER_COMM_AMT) as DER_COMM_AMT,
        SUM(CASE WHEN MNTH_YR_PART_EFF_TO != MNTH_YR_PART_LAST_DAY THEN out_DER_COMM_AMT ELSE 0 END) as out_COMM_ADDED_AMT,
        MAX(out_TRAN_PREM_AMT) as TRAN_PREM_AMT,
        MAX(TRAN_COMM_AMT1) as TRAN_COMM_AMT,
        MAX(DER_TRAN_PREM_AMT) as DER_TRAN_PREM_AMT,
        MAX(DER_TRAN_COMM_AMT) as DER_TRAN_COMM_AMT,
        SUM(CASE WHEN MNTH_YR_PART_EFF_TO != MNTH_YR_PART_LAST_DAY THEN DER_TRAN_PREM_AMT ELSE 0 END) as TRAN_PREM_ADDED_AMT,
        SUM(CASE WHEN MNTH_YR_PART_EFF_TO != MNTH_YR_PART_LAST_DAY THEN DER_TRAN_COMM_AMT ELSE 0 END) as TRAN_COMM_ADDED_AMT,
        MAX(out_CONTR_PREM_AMT) as CONTR_PREM_AMT,
        MAX(DER_CONTR_PREM_AMT) as DER_CONTR_PREM_AMT,
        SUM(CASE WHEN MNTH_YR_PART_EFF_TO != MNTH_YR_PART_LAST_DAY THEN DER_CONTR_PREM_AMT ELSE 0 END) as CONTR_PREM_ADDED_AMT,
        MAX(SRC_LN_OF_BUSN_CD411) as SRC_LN_OF_BUSN_CD41,
        MAX(out_CONTR_COMM_AMT41) as CONTR_COMM_AMT41,
        MAX(DER_CONTR_COMM_AMT41) as DER_CONTR_COMM_AMT41,
        SUM(CASE WHEN MNTH_YR_PART_EFF_TO != MNTH_YR_PART_LAST_DAY THEN DER_CONTR_COMM_AMT41 ELSE 0 END) as CONTR_COMM_ADDED_AMT,
        MAX(CRCY_CD1) as CRCY_CD,
        MAX(TRAN_CRCY_CD1) as TRAN_CRCY_CD,
        MAX(CONTR_CRCY_CD1) as CONTR_CRCY_CD,
        MAX(SRC_LN_OF_BUSN_CD411) as SRC_LN_OF_BUSN_CD411,
        MAX(out_CONTR_COMM_AMT41) as out_CONTR_COMM_AMT41,
        MAX(CRCY_CD1) as CRCY_CD1,
        MAX(TRAN_CRCY_CD1) as TRAN_CRCY_CD1,
        MAX(CONTR_CRCY_CD1) as CONTR_CRCY_CD1
    from int_srt_dates
    group by 
        PRTCLR_MONY_PROVSN_ID,
        ETL_SYS_NM
)
select * from int_agg_last_mnth

--End-DBShift