{{ config(materialized='view', tags=["m_FDS_CTRL_SPRD_MNTHLY_AMTS_ATOMIC_LAST_INS"]) }}

-- SQ_ctrl_sprd_mnthly_amts_temp1
with raw_source as (
    select * from {{ source('PostgreSQL35W', 'ctrl_sprd_mnthly_amts_temp_1') }} ctrl_sprd_mnthly_amts_temp_1
),

source_data as (
    select
        src.prtclr_mony_provsn_id,
        src.agmt_anchr_id,
        src.eff_fm_tistmp,
        src.eff_to_tistmp,
        src.base_amt,
        src.out_base_amt,
        src.out_monthly_date,
        src.out_mnth_yr_part_eff_to,
        src.out_mnth_yr_part_last_day,
        src.v_exp_date_diff,
        src.daily_amt,
        src.out_trl_sprd_ind,
        src.out_mnth_yr_part_trl_sprd_2yr_last_day,
        src.out_trl_sprd_2yr_base_amt,
        src.out_trl_sprd_2yr_last_mnth_rem_days,
        src.out_trl_sprd_rem_term_dly_amt,
        src.out_eff_md_yr_mo,
        src.covg_cmpnt_agmt_anchr_id,
        src.etl_sys_nm,
        src.out_eff_md_yr_mo_dflt,
        src.in_comm_amt,
        src.in_comm_daily_amt,
        src.out_comm_amt,
        src.out_trl_sprd_2yr_comm_amt,
        src.out_trl_sprd_rem_term_comm_dly_amt,
        src.out_der_comm_amt,
        src.in_tran_prem_amt,
        src.in_tran_comm_amt,
        src.in_dly_tran_comm_amt,
        src.in_dly_tran_prem_amt,
        src.out_trl_sprd_2yr_tran_prem_amt,
        src.out_trl_sprd_rem_term_tran_prem_dly_amt,
        src.out_trl_sprd_2yr_tran_comm_amt,
        src.out_trl_sprd_rem_term_tran_comm_dly_amt,
        src.out_der_tran_prem_amt,
        src.out_der_tran_comm_amt,
        src.in_contr_prem_amt,
        src.in_dly_contr_prem_amt,
        src.out_contr_prem_amt,
        src.out_trl_sprd_2yr_contr_prem_amt,
        src.out_trl_sprd_rem_term_contr_prem_dly_amt,
        src.src_ln_of_busn_cd,
        src.in_contr_comm_amt,
        src.in_dly_contr_comm_amt,
        src.out_contr_comm_amt,
        src.out_trl_sprd_2yr_contr_comm_amt,
        src.out_trl_sprd_rem_term_contr_comm_dly_amt,
        src.crcy_cd,
        src.tran_crcy_cd,
        src.contr_crcy_cd,
        src.out_pop_info_id,
        src.out_batch_id,
        src.v_chk_mnth_part_fm,
        src.v_chk_mnth_part_to,
        src.v_days_in_mnth,
        src.v_mnth_yr_part_trl_sprd_2yr_last_day,
        src.v_mnth_yr_part_last_day,
        src.v_trl_sprd_2yr_dly_amt,
        src.v_trl_sprd_rem_term_dly_amt,
        src.v_trl_sprd_2yr_comm_dly_amt,
        src.v_trl_sprd_rem_term_comm_dly_amt,
        src.v_trl_sprd_2yr_tran_prem_dly_amt,
        src.v_trl_sprd_rem_term_tran_prem_dly_amt,
        src.v_trl_sprd_2yr_tran_comm_dly_amt,
        src.v_trl_sprd_rem_term_tran_comm_dly_amt,
        src.v_trl_sprd_2yr_contr_prem_dly_amt,
        src.v_trl_sprd_rem_term_contr_prem_dly_amt,
        src.v_trl_sprd_2yr_contr_comm_dly_amt,
        src.v_trl_sprd_rem_term_contr_comm_dly_amt,
        src.v_trl_sprd_2yr_contr_comm_dly_amt as v_trl_sprd_2yr_contr_comm_dly_amt_1,
        src.v_trl_sprd_rem_term_comm_dly_amt as v_trl_sprd_rem_term_comm_dly_amt_1,
        src.v_trl_sprd_2yr_tran_prem_dly_amt as v_trl_sprd_2yr_tran_prem_dly_amt_1,
        src.v_trl_sprd_rem_term_tran_prem_dly_amt as v_trl_sprd_rem_term_tran_prem_dly_amt_1,
        src.v_trl_sprd_2yr_tran_comm_dly_amt as v_trl_sprd_2yr_tran_comm_dly_amt_1,
        src.v_trl_sprd_rem_term_tran_comm_dly_amt as v_trl_sprd_rem_term_tran_comm_dly_amt_1,
        src.v_trl_sprd_2yr_contr_prem_dly_amt as v_trl_sprd_2yr_contr_prem_dly_amt_1,
        src.v_trl_sprd_rem_term_contr_prem_dly_amt as v_trl_sprd_rem_term_contr_prem_dly_amt_1,
        src.v_trl_sprd_rem_term_contr_comm_dly_amt as v_trl_sprd_rem_term_contr_comm_dly_amt_1
    from raw_source src
)

select * from source_data

--End-DBShift